### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by DevAlien** [Grrrben/gocoin#19]
I there, I wanted to build my own blockchain in golang and I came across your project.

I have a couple of questions for you.
Is a client a node? If so why calling it `client`?

for blockchains is the right behaviour that you get rewarded for mining even if there are no transactions? I see that this is something we see here.

**Comment by Grrrben** [comment]
Hi DevAlien, thanks for your interest in this project. 

So first off, you're absolutely right. A client is actually a node and the latter is a way more descriptive name so that has to be changed in the future. If you're planning on using this repo as a start off point, feel free to send me a pull request on the matter, would appriciate it. (I am traveling for a few weeks thus not writing a lot of code).

The mining is currently implemented as you described. As I don't have a special usecase yet, I have not written any business rules regarding the mining and awards, only a proof with a certain difficulty is added. 

Good luck with your project.
